# Generated by Django 3.2 on 2021-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile Page', 'verbose_name_plural': 'Profile Page'},
        ),
    ]
